### ISSUE TITLE
Lot's of `signalfx-metadata: trying to parse collectd version failed [Errno 2] No such file or directory` in docker output

### ISSUE THREAD

**Issue by awk** [signalfx/docker-collectd#2]
After doing a docker run --privileged --env-file=collectd.env -v /proc:/mnt/proc <imageid> I'm seeing a lot of messages in the stdout of the docker command :

[2015-10-28 18:33:45] signalfx-metadata: trying to parse collectd version failed [Errno 2] No such file or directory

Repeated roughly every 10 seconds.

Is there some portion of the signalfx plugin which isn't entirely happy being in a docker?

**Comment by mdubbyap** [comment]
Sorry, this is a known issue and will be fixed in the next version of the plugin. Because of pid mapping inside the container we're looking for a pid that doesn't exist when the host systems proc is mounted.  This is why collectd_version is sent in as UNKNOWN as well. I have it fixed but it's with a bunch of other untested stuff that needs to all be shipped together. Will update the docker image when it's fixed.  Sorry for any inconvenience.

**Comment by awk** [comment]
Yeah - that makes sense, after writing this I went digging into the signal fx plugin and saw the source of the error and thought "'ruh-roh' that's going to need changing."

**Comment by mdubbyap** [comment]
Just released a new version of the docker image that has this fixed.  Please check it out!
